#!/usr/bin/zsh

HD="/home/ghz/solar_power_wx"
YD="$(date +%Y)"
DD="$(date +%Y%m%d)"
DATD="${HD}/data/${YD}"


CHG_BAL="$( ${HD}/power_balance "${DATD}/solar_power.${DD}" | grep Charge )"

echo -e "${DD}\t${CHG_BAL}" >> "${DATD}/solar_power.charge_bal.${YD}"
