#!/usr/bin/zsh

echo "Goodbye cruel European insolation!" | /usr/bin/mail -s "$(/bin/hostname) is dying. $(/bin/date -u +%FT%T%Z)" root

# give the mail time to send. good luck.
sleep 8

/bin/sync
/bin/sync

# we have a sudo rule for this
/usr/bin/sudo /sbin/halt
