#!/usr/bin/python3     

import time, datetime, busio, board
import adafruit_veml6070
import adafruit_tsl2561
     
i2c = busio.I2C(board.SCL, board.SDA)

uv = adafruit_veml6070.VEML6070(i2c, 'VEML6070_4_T')
vis_ir = adafruit_tsl2561.TSL2561(i2c)

# init this tsl sensor
vis_ir.enabled = True
time.sleep(1)
vis_ir.gain = 0
vis_ir.integration_time = 1

# first reads are often kinda bogus
try:
	lux = "%.2f" % vis_ir.lux
	uvr = "%d" % uv.uv_raw
	bb = "%d" % vis_ir.broadband
	ir = "%d" % vis_ir.infrared
except:
	printf("inital read failed.")
     
while True:
	ts = datetime.datetime.fromtimestamp(time.time()).strftime("%FT%TZ")

	# gnuplot and all my other code will accept "??" for "went sideways"
	try:
		lux = "%.2f" % vis_ir.lux
	except :
		lux = "??"
	try:
		uvr = "%d" % uv.uv_raw
	except:
		uvr = "??"
	try:
		bb = "%d" % vis_ir.broadband
	except:
		bb = "??"
	try:
		ir = "%d" % vis_ir.infrared
	except:
		ir = "??"

	dat = "lux: %s, UV: %s, BB: %s, IR, %s" % (lux, uvr, bb, ir)
	print(ts, "\t", dat, flush=True)
	time.sleep(1)
