#!/bin/sh

# the plan is, this script is called with a cron job sth like so:
#minute	hour	mday	month	wday	command
# *	*	*	*	*	/home/ghz/solar_power_wx/solar_sync

/home/ghz/solar_power_wx/grab_48h
gnuplot /home/ghz/solar_power_wx/solar_power.gnuplot
/usr/bin/rsync -e 'ssh -q' --timeout=60 -ur /home/ghz/solar_power_wx/* wx8_sync:/wx8/
